dbt_tutorial:
  outputs:
    dev:
      dataset: de4e
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/ihwalim/dbt_project/bigquery_credentials.json
      location: asia-northeast3
      method: service-account
      priority: interactive
      project: pseudolab-de4e-tutorial
      threads: 1
      type: bigquery
  target: dev
